blank_issues_enabled: false
contact_links:
  - name: The Discussions tab
    url: https://github.com/NanashiTheNameless/VintageShock/discussions
    about: This is where to go for general questions and support requests.
